# Generated by Django 4.2.2 on 2023-06-20 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0002_articles_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Опубликовать')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('articl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.articles', verbose_name='Статья')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['id'],
            },
        ),
    ]
