# Generated by Django 4.2.2 on 2023-06-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['id'], 'verbose_name': 'комментарии', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
    ]
