# Generated by Django 4.1.7 on 2023-03-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_name_product_old_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='is_activated',
        ),
    ]
