# Generated by Django 4.1.7 on 2023-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_cart_basket_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Товар'),
        ),
    ]
