# Generated by Django 4.1.7 on 2023-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_basket_products_delete_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='published',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
