# Generated by Django 4.1.7 on 2023-04-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_advuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
