# Generated by Django 4.1.7 on 2023-04-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_advuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
