# Generated by Django 4.1.7 on 2023-04-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_delete_advuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('messages', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщение',
                'ordering': ['name'],
            },
        ),
    ]
